---
name: ✨ Feature Request
description: Propose a new OpenCAD website feature or enhancement
labels: ["type: feature"]
body:
  - type: markdown
    attributes:
      value: >
        **NOTE:** This form is only for submitting well-formed proposals to extend or modify
        the OpenCAD website in some way. If you're trying to solve a problem but can't figure out how, or if
        you still need time to work on the details of a proposed new feature, please start a
        [discussion](https://github.com/opencad-community/opencad/discussions) instead.
  - type: dropdown
    attributes:
      label: Feature type
      options:
        - New functionality/content
        - Change to existing functionality/content
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed functionality
      description: >
        Describe in detail the new feature or behavior you are proposing. Include any specific changes
        to work flows, content, and/or the user interface. The more detail you provide here, the
        greater chance your proposal has of being discussed. Feature requests which don't include an
        actionable implementation plan will be rejected.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Use case
      description: >
        Explain how adding this functionality would benefit OpenCAD website users. What need does it address?
    validations:
      required: true
  - type: textarea
    attributes:
      label: External dependencies
      description: >
        List any new dependencies on external libraries or services that this new feature would
        introduce. For example, does the proposal require the different icon library?
        (Not all new features introduce new dependencies.)
